<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;

function jsonld_markup_jsonld_alter_normalized_array(EntityInterface $entity, array &$normalized, array $context) {
  if(($node = \Drupal::routeMatch()->getParameter('node'))){
    if ($node instanceof \Drupal\node\NodeInterface) {
      $nid = $node->id();
      $node = \Drupal\node\Entity\Node::load($nid);
      if($node->hasField('field_schema_type')){
        $my_field_data = $node->get('field_schema_type')->getValue();
        $my_field_value= $my_field_data [0]['value'];
      }
    }
  }
  $normalized['@graph']['0']['@type'] = ["http://schema.org/" . $my_field_value];
}


/**
 * Implements hook_page_attachments_alter().
 *
 * Load all meta tags for this page, then separate out the structured data.
 *
 */
function jsonld_markup_page_attachments_alter(array &$attachments) {

  $currentURL = $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['HTTP_HOST'] . strtok($_SERVER['REQUEST_URI'], '?') . '?_format=jsonld';

  try {
    $response = \Drupal::httpClient()->request('GET', $currentURL);
    $jsonld= $response->getBody()->getContents();
  
  } catch (\Exception $e) {
    $jsonld = $e->getMessage();
  }

  $attachments['#attached']['html_head'][] = [
    [
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => $jsonld,
      '#attributes' => ['type' => 'application/ld+json'],
    ],
  ];
}
