name: Automated testing

on: [push]

jobs:
  call-testing-workflow:
    uses: digitalutsc/reusable_workflows/.github/workflows/ci-testing.yml@main
    with:
      module_name: jsonld_markup
      composer_name: drupal/jsonld_markup
      test_suite: null
